steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/safekeep-382003/safekeep", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/safekeep-382003/safekeep"]
  - name: gcr.io/cloud-builders/gcloud
    args:
      [
        "run",
        "deploy",
        "safekeep",
        "--image",
        "gcr.io/safekeep-382003/safekeep",
        "--region",
        "us-west1",
      ]
