name: Deploy to Google Cloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: your-project-id
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/your-project-id/your-image-name:$GITHUB_SHA .
          docker push gcr.io/your-project-id/your-image-name:$GITHUB_SHA

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy your-service-name \
            --image gcr.io/your-project-id/your-image-name:$GITHUB_SHA \
            --platform managed \
            --region your-region \
            --allow-unauthenticated
