name: Run Tests

on:
  push:
    # branches:
    #  - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Pull PostgreSQL image
        run: docker pull postgres

      - name: Create and start Docker container
        run: docker run --name mock-postgres -e POSTGRES_PASSWORD=mysecretpassword -p 5432:5432 -d postgres

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE
          go test ./...
          # Add additional test commands if needed

      - name: Stop and remove Docker container
        run: |
          docker stop mock-postgres
          docker rm mock-postgres
